### ISSUE TITLE
ESLint Plugin

### ISSUE THREAD

**Issue by ChakshuGautam** [antfu/case-police#116]
Would love to contribute to one if it does not exist. :)

**Comment by antfu** [comment]
Happy to see that!

**Comment by jaw52** [comment]
> Happy to see that!

Hello, I have submitted a pull request regarding `eslint-plugin`. , which may not be perfect.  Could you kindly review it and let me know if there's anything I can do to improve it?  Thank you for your time and consideration.

https://github.com/antfu/case-police/pull/153
