### ISSUE TITLE
Vale package?

### ISSUE THREAD

**Issue by kodster28** [antfu/case-police#161]
### Clear and concise description of the problem

We currently have a Vale workflow hooked up to our [docs repo](https://github.com/cloudflare/cloudflare-docs).

I'd love to utilize Case Police w/in that same workflow, but as it stands I think the best we'd get is two separate checks (with the Case Police integrated through GitHub actions).

### Suggested solution

Realize I'm just suggesting a bunch of work that y'all could do to save myself the trouble... but any thoughts on adding a [Vale Package](https://vale.sh/hub/) for Case Police?

I'd love to be able to hook into the stuff y'all already keep maintained but then pull into our current Vale workflow.

At the moment, it ends up being a process a lot more like https://github.com/cloudflare/cloudflare-docs/pull/16564 or https://github.com/DataDog/datadog-vale/blob/main/styles/SIEM-Names/namecase.yml.

I'd guess some customization would definitely continue regardless, but y'alls list would be a great starting point (especially if it were made available in more places).

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Thank you for bringing this up! I am up to it, but probably won't do it my own as I don't use Vale myself. The data in this repo is saved as JSON to support such external usages, feel free to build anything on top of them. For now I will mark this issue as "not planned". Thanks

**Comment by kodster28** [comment]
> Thank you for bringing this up! I am up to it, but probably won't do it my own as I don't use Vale myself. The data in this repo is saved as JSON to support such external usages, feel free to build anything on top of them. For now I will mark this issue as "not planned". Thanks

Gotcha gotcha. Totally get it + thanks for the context here
